# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.define "{{ cookiecutter.slug }}" do |{{ cookiecutter.slug }}|
    {{ cookiecutter.slug }}.vm.box_url = "https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-36-1.5.x86_64.vagrant-libvirt.box"
    {{ cookiecutter.slug }}.vm.box = "f36-cloud-libvirt"
    {{ cookiecutter.slug }}.vm.hostname = "{{ cookiecutter.slug }}.test"

    {{ cookiecutter.slug }}.vm.synced_folder '.', '/vagrant', disabled: true
    {{ cookiecutter.slug }}.vm.synced_folder ".", "/home/vagrant/{{ cookiecutter.slug }}", type: "sshfs"


    {{ cookiecutter.slug }}.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 2048 
    end

    {{ cookiecutter.slug }}.vm.provision "ansible" do |ansible|
      ansible.playbook = "devel/ansible/playbook.yml"
      ansible.config_file = "devel/ansible/ansible.cfg"
      ansible.verbose = true
    end
  end

end
